import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono, Google_Sans, Inter ,Young_Serif,IBM_Plex_Mono} from 'next/font/google'
import './globals.css'
import { QueryClientProvider } from '@tanstack/react-query'
import { queryClient } from '@/lib/queryClient'

const gSans = Google_Sans({
  subsets: ["latin"],
  variable: "--font-gsans",
  display: "swap",
});

const youngSerif = Young_Serif({
  weight: '400',
  variable: '--font-young-serif',
  subsets: ['latin'],
})

const ibmPixelMono = IBM_Plex_Mono({
  weight: ['400', '500', '600', '700'],  
  variable: '--font-ibm-plex-mono',
  subsets: ['latin'],
})

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})



export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <QueryClientProvider client={queryClient}>

        <body className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${gSans.variable} ${youngSerif.variable} text-white antialiased`}>
          
          {children}
        </body>
        </QueryClientProvider>
      </html>
    </ClerkProvider>
  )
}